### ISSUE TITLE
Restore snapshot fails

### ISSUE THREAD

**Issue by fab33** [LINBIT/linstor-proxmox#5]
Create a snapshot from Proxmox web gui works fine and we can list the snapshot with "drbdmanage list-snapshots" but when we try to restore the snapshot it fails with the message "snapshot restore is not implemented yet".

**Comment by rck** [comment]
Where exactly didn't you understand what I told you? Can/Should I explain it again?

https://github.com/LINBIT/drbdmanage-proxmox/issues/2

**Comment by fab33** [comment]
Ok, I just copy the issue from drbdmanage-proxmox but it's the same in linstor-proxmox. You can't restore snapshot from the GUI and it will be a great feature.

**Comment by acidrop** [comment]
The traditional restore approach of PVE, is useless and very slow. If you want to restore a VM quickly, just use the command line. This is explained in the LINSTOR documentation.

**Comment by elonen** [comment]
The current error message is not very helpful:
`DRBD snapshot rollback is not implemented, please use 'linstor' to recover your data, use 'qm unlock' to unlock your VM at /usr/share/perl5/PVE/Storage/Custom/LINSTORPlugin.pm line 441`

If it can't be done automatically, could it perhaps include some hints on how to do the rollback manually?

**Comment by rck** [comment]
As an update to the whole "in place" vs. "new resource" topic: In place is now on the roadmap, so eventually this should be possible. (No, I don't know when exactly)

**Comment by greb-o** [comment]
Hello,
The implementation of the snapshot restore feature in the proxmox console would be of real interest. Now, do you have any idea about when this feature will be available?
thank you,

**Comment by rck** [comment]
In contrast to DRBDManage, LINSTOR has (limited) support for rolling back snapshots. This fits Proxmox's model a lot better. With the new API/abstraction ob the current release and by using the REST-client, it should be pretty easy to code something usable. That said, I'm too busy with other projects to just work on it because it would be fun. Perl is never fun. So this has to wait for a) a contribution (I will obviously help getting patches in shape), or b) a customer that requests it.
